### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by brandleesee** [fastrizwaan/gnome-40-win11#1]
I do not have the skills to create a _pitch black_ shell.
Would you be interested in having a light theme (the current one) and a dark mode?
Thank you in advance.

**Comment by fastrizwaan** [comment]
Here are the things which needs to be dark/light:

1. gnome-shell theme (by default it is dark) you can use .css file to change colors inside the tar file
2. Arc theme
3. gtk style (gnome-tweaks) (dark-adwaita)
4. icon theme

You can tweak them. I am not using this, it was just created for fun.

**Comment by brandleesee** [comment]
Meant to thank you way earlier than this...
So, thank you!
